substitutions:
  name: esp8266_masterbath-iaq
  friend: 8266 QuantumSync Solutions IAQ-UNO
  version: "24.05.6.800.8266"
  device_description: ${friendly_name} made by QuantumSync Solutions - IAQ-UNO Version':' ${version}.

esphome:
  name: "${name}"
  friendly_name: MasterBath IAQ
  project:
    name: "IAQuno.QuantumSyncSolutions"
    version: "${version}"

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"
    
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret IAQ_Wifi_Portal_SSID
    password: !secret IAQ_Wifi_Portal_PWD
  domain: !secret IAQ_Wifi_Domain

web_server:
  port: 80

font:
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20

  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: roboto_16
    size: 16

  - file: 'ariblk.ttf'
    id: font1
    size: 14

time:
  - platform: homeassistant
    id: esptime

sensor:
  - platform: homeassistant
    id: HAlocal_IP
    entity_id: sensor.local_ip
    internal: true

i2c:
  sda: D2
  scl: D1

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    update_interval: 15s
    lambda: |-
      it.printf(0, 0, id(roboto_16), "Current Time:");
      it.strftime(0, 40, id(font1), "%H:%M", id(esptime).now());

    
