
substitutions:
  name: iaq_uno
  friend: QuantumSync Solutions IAQ-UNO
  version: "24.01.24"
  device_description: ${friendly_name} made by QuantumSync Solutions - IAQ-UNO Version':' ${version}.

esphome:
  name: "${name}"
  friendly_name: "${friend}"
  comment: "${friend}"
  platformio_options:
    board_build.flash_mode: dio
    
  on_boot:
  - priority: 900.0
    then:
      - lambda: |-
          id(cpu_speed) = ESP.getCpuFreqMHz();

  project:
    name: "IAQuno.QuantumSyncSolutions"
    version: "${version}"

globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "TgQxi0unvoCFsohL9Ou3JkU5VI/OLQ9yXn+sXqXPz4c="

ota:
  password: "d645ddda2ce7fe34835b17e62a7339c2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "QSS-IAQ UNO Setup"
    password: "qssiaqsetup"
  domain: .mjhhome.com

captive_portal:

web_server:
  port: 80

output:
  - platform: ledc
    pin: 2
    id: output_ledpin2

light:
  - platform: monochromatic
    name: "LED Locate"
    output: output_ledpin2

i2c:
  - id: i2c0
    sda: 21
    scl: 22
    scan: true
    frequency: 800kHz

tca9548a:
  - id: multiplex0
    i2c_id: i2c0
    channels:
      - bus_id: multiplex0channel0
        channel: 0
      - bus_id: multiplex0channel1
        channel: 1
      - bus_id: multiplex0channel2
        channel: 2

bme680_bsec:
  - id: bme680
    i2c_id: "multiplex0channel0"
    address: 0x77
    state_save_interval: 6h
    sample_rate: lp
    iaq_mode: static
    
sensor:
  - platform: bh1750 #BH1750 ILLUMINATION SENSOR SETUP
    name: "LUX"
    id: luxlight
    address: 0x23
    i2c_id: multiplex0channel1
    update_interval: 2s

  - platform: bme680_bsec #BME680 TEMP/BARO/HUMIDITY/C02/GAS/IAQ/BVOC SENSOR SETUP
    bme680_bsec_id: bme680
    temperature:
      name: "Temperature"
      accuracy_decimals: 1
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      id: temperaturebme
    pressure:
      name: "Barometric Pressure"
      accuracy_decimals: 5
      id: pressure
    humidity:
      name: "Humidity"
      id: humiditybme
      accuracy_decimals: 1
    gas_resistance:
      name: "Gas Resistance"
      id: gas
      accuracy_decimals: 5
    co2_equivalent:
      name: "CO2 Equivalent"
    iaq:
      name: "IAQ"
      id: iaq
    breath_voc_equivalent:
      name: "Intake Breath VOC Equivalent"
      filters:
        - median

  - platform: sgp30 #SP30 eC02/TVOC SENSOR SETUP
    i2c_id: multiplex0channel2
    eco2:
      name: "eCO2"
      accuracy_decimals: 1
    tvoc:
      name: "TVOC"
      accuracy_decimals: 1
    address: 0x58
    update_interval: 1s
    compensation: 
      temperature_source: temperaturebme
      humidity_source: humiditybme

  - platform: wifi_signal #WIFI SIGNAL STRENGTH SETUP 
    name: "IAQ UNO - WiFi Signal"
    update_interval: 120s

  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"

  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 60s

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: IAQ Sensor Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

binary_sensor:
  - platform: gpio
    pin: 4
    name: "PIR Sensor"
    device_class: motion

text_sensor: #BME680 LAMBDA READOUT SETUP
  - platform: bme680_bsec 
    bme680_bsec_id: bme680
    iaq_accuracy:
      name: "IAQ Accuracy"
      
  - platform: template
    name: "IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }

  - platform: template
    name: "LUX Brightness"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(luxlight).state) <= 50) {
        return {"Dark"};
      }
      else if (int(id(luxlight).state) >= 51 && int(id(iaq).state) <= 200) {
        return {"Dim"};
      }
      else if (int(id(luxlight).state) >= 201 && int(id(iaq).state) <= 550) {
        return {"Inside Lights ON"};
      }
      else if (int(id(luxlight).state) >= 551 && int(id(iaq).state) <= 1000) {
        return {"Sunny Day"};
      }
      else if (int(id(luxlight).state) >= 1001 && int(id(iaq).state) <= 10000) {
        return {"Direct Sun"};
      }
      else if (int(id(luxlight).state) >= 10000) {
        return {"Extremely BRIGHT"};
      }
      else {
        return {"error"};
      }

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "IAQ Sensor Powercycle"
